"use client";
import Image from "next/image";
import { motion } from "framer-motion";
import { staggerContainer, staggerChild } from "@/lib/motion";

const generations = [
  { seed: "gen1", prompt: "dark cinematic gaming thumbnail, RGB lighting, dramatic" },
  { seed: "gen2", prompt: "bright vlog thumbnail, travel photography, golden hour" },
  { seed: "gen3", prompt: "tech review thumbnail, clean minimal, product on white" },
  { seed: "gen4", prompt: "cooking channel, vibrant food photography, warm tones" },
  { seed: "gen5", prompt: "finance YouTube, professional graph, navy and gold" },
  { seed: "gen6", prompt: "fitness transformation, before/after, bold red accent" },
  { seed: "gen7", prompt: "scary story at night, horror atmosphere, red eyes" },
  { seed: "gen8", prompt: "music producer, neon studio, purple ambient light" },
  { seed: "gen9", prompt: "travel vlog bali, aerial drone, turquoise water" },
  { seed: "gen10", prompt: "reaction video, expressive face, bold text overlay" },
  { seed: "gen11", prompt: "coding tutorial, dark IDE, colorful syntax highlight" },
  { seed: "gen12", prompt: "podcast episode, two hosts, microphone foreground" },
];

export function GenerationsGrid() {
  return (
    <section className="py-24 px-6">
      <div className="max-w-7xl mx-auto">
        <motion.div
          variants={staggerContainer}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-80px" }}
          className="mb-12 text-center"
        >
          <motion.h2 variants={staggerChild} className="text-4xl font-bold tracking-tight mb-4">
            See what&apos;s possible
          </motion.h2>
          <motion.p variants={staggerChild} className="text-lg text-muted-foreground">
            Real thumbnails generated by Pixify users.
          </motion.p>
        </motion.div>

        <div className="columns-2 md:columns-3 lg:columns-4 gap-3">
          {generations.map((gen) => (
            <div
              key={gen.seed}
              className="group relative break-inside-avoid mb-3 rounded-lg overflow-hidden bg-card border border-border"
            >
              <div className="relative aspect-[16/9]">
                <Image
                  src={`https://picsum.photos/seed/${gen.seed}/480/270`}
                  alt=""
                  fill
                  className="object-cover"
                  sizes="(max-width: 768px) 50vw, (max-width: 1024px) 33vw, 25vw"
                />
              </div>
              {/* Hover prompt overlay */}
              <div className="absolute inset-0 bg-gradient-to-t from-background/90 via-background/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-200 flex items-end p-3">
                <p className="text-xs text-muted-foreground leading-snug">{gen.prompt}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
